export const popularProducts = [
    {
      id: 1,
      img :"https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    },
    {
      id:2,
      img:"https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    },
    {
      id:3,
      img:"https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    },
    {
      id:4,
      img:"https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
    },
    {
      id:5,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNY4Nw44nTd-vhPHOYilhrlDRVKGkipN5SKA&usqp=CAU",
    },
    {
      id:6,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR074-x0SBw_jK2lSDXhhdckuF64eOTc-cq9g&usqp=CAU",
    },
    {
      id:7,
      img :"https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    },
    {
      id:8,
      img:"https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    },
     {
      id:9,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgNrAeptZaJ14jJwJxAMtD81V60DErjHLffA&usqp=CAU",
    },
     {
      id:10,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvEJelwPFGAhryQqQMUT3Z5ADwwQ9sa1va8A&usqp=CAU",
    },
      {
      id:11,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSagi9x3mOhgc4-ttxwqaJBefJGWBe-nofHNw&usqp=CAU",
    },
      {
      id:12,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrGBdSvzDZFkrY3qtjZCcoP2OJEdlkArEurw&usqp=CAU",
    },
  ]
